const ApiConst: any = {
 GET_PAGE: "/page",
 GET_POST_TYPE: "/admin/post",
 GET_POST_CATEGORY: "/admin/category",
 GET_PAGE_TYPE: "/admin/page-type",
 ADD_PAGE_ITEM: "/admin/page-item/",
 GET_POST_BY_CATEGORY: "/admin/category-item",
 GET_CONFIG: "/admin/config",
 GET_CONFIG_OPEN_LINK: "/admin/config/open-link",
 GET_CONFIG_FAKE_DATA: "/admin/config/fake-data",
 GET_CONFIG_ENABLE_LOGIN: "/admin/config/enable-login",
 CHANGE_SETTING: "/admin/config",
 GET_USERS: "/admin/user",
 GET_POST: "/admin/post/posts",
 ACTION_POST: "/admin/post",
 GET_LIST_BY_TYPE_POST: "/admin/post/posts",
 GET_LIST_BY_TYPE_GAME_CARD: "/admin/post/game-card",
 GET_LIST_BY_TYPE_ADS: "/admin/post/ads",
 GET_LIST_BY_TYPE_GAME_MOBILE: "/admin/post/game-mobile",
 GET_LIST_BY_TYPE_LIVESTREAM: "/admin/post/livestream",
 GET_LIST_BY_TYPE_NOTIFY: "/admin/post/notify",
 ACTION_GAME_CARD: "/admin/game-card",
 ACTION_ADS: "/admin/ads",
 ACTION_GAME_MOBILE: "/admin/game-mobile",
 ACTION_LIVESTREAM: "/admin/livestream",
 ACTION_NOTIFY: "/admin/notify",
}

export default ApiConst